# Generated by Django 4.1.2 on 2023-02-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coin_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerForSpecificCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('circulating_supply', models.IntegerField()),
                ('total_supply', models.IntegerField(null=True)),
                ('max_supply', models.IntegerField(null=True)),
                ('beta_value', models.FloatField(null=True)),
                ('first_data_at', models.DateTimeField(null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('price', models.BigIntegerField()),
                ('volume_24h', models.BigIntegerField()),
                ('volume_24h_change_24h', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('market_cap_change_24h', models.FloatField()),
                ('percent_change_15m', models.FloatField()),
                ('percent_change_30m', models.FloatField()),
                ('percent_change_1h', models.FloatField()),
                ('percent_change_6h', models.FloatField()),
                ('percent_change_12h', models.FloatField()),
                ('percent_change_24h', models.FloatField()),
                ('percent_change_7d', models.FloatField()),
                ('percent_change_30d', models.FloatField()),
                ('percent_change_1y', models.FloatField()),
                ('ath_price', models.BigIntegerField()),
                ('ath_date', models.DateTimeField()),
                ('percent_from_price_ath', models.FloatField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin_profile.coinprofile')),
            ],
            options={
                'verbose_name_plural': 'ticker for a specific coin',
            },
        ),
    ]
