# Generated by Django 4.1.7 on 2023-02-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_for_specific_coin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerforspecificcoin',
            name='first_data_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tickerforspecificcoin',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
