# Generated by Django 4.1.2 on 2023-03-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_for_specific_coin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickerforspecificcoin',
            old_name='percent_change_15m',
            new_name='change_percentage',
        ),
        migrations.RenameField(
            model_name='tickerforspecificcoin',
            old_name='percent_change_12h',
            new_name='year_high',
        ),
        migrations.RenameField(
            model_name='tickerforspecificcoin',
            old_name='percent_change_1h',
            new_name='year_low',
        ),
        migrations.RemoveField(
            model_name='tickerforspecificcoin',
            name='percent_change_1y',
        ),
        migrations.RemoveField(
            model_name='tickerforspecificcoin',
            name='percent_change_24h',
        ),
        migrations.RemoveField(
            model_name='tickerforspecificcoin',
            name='percent_change_30d',
        ),
        migrations.RemoveField(
            model_name='tickerforspecificcoin',
            name='percent_change_30m',
        ),
        migrations.RemoveField(
            model_name='tickerforspecificcoin',
            name='percent_change_6h',
        ),
        migrations.RemoveField(
            model_name='tickerforspecificcoin',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='tickerforspecificcoin',
            name='rank',
        ),
    ]
