# Generated by Django 4.1.2 on 2023-03-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_for_specific_coin', '0002_rename_percent_change_15m_tickerforspecificcoin_change_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerforspecificcoin',
            name='ath_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tickerforspecificcoin',
            name='ath_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tickerforspecificcoin',
            name='change_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tickerforspecificcoin',
            name='circulating_supply',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tickerforspecificcoin',
            name='market_cap',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tickerforspecificcoin',
            name='market_cap_change_24h',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tickerforspecificcoin',
            name='percent_from_price_ath',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tickerforspecificcoin',
            name='volume_24h',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tickerforspecificcoin',
            name='volume_24h_change_24h',
            field=models.FloatField(null=True),
        ),
    ]
