# Generated by Django 4.1.2 on 2023-03-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_for_specific_coin', '0003_alter_tickerforspecificcoin_ath_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickerforspecificcoin',
            name='ath_date',
        ),
        migrations.RemoveField(
            model_name='tickerforspecificcoin',
            name='ath_price',
        ),
        migrations.RemoveField(
            model_name='tickerforspecificcoin',
            name='coin_id',
        ),
        migrations.RemoveField(
            model_name='tickerforspecificcoin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tickerforspecificcoin',
            name='percent_from_price_ath',
        ),
    ]
