# Generated by Django 4.1.2 on 2023-03-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_for_specific_coin', '0004_remove_tickerforspecificcoin_ath_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerforspecificcoin',
            name='year_high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tickerforspecificcoin',
            name='year_low',
            field=models.FloatField(null=True),
        ),
    ]
