# Generated by Django 4.1.2 on 2023-03-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_for_specific_coin', '0005_alter_tickerforspecificcoin_year_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerforspecificcoin',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
    ]
