# Generated by Django 4.1.2 on 2023-03-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_for_specific_coin', '0007_remove_tickerforspecificcoin_volume_24h_change_24h'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerforspecificcoin',
            name='change',
            field=models.FloatField(null=True),
        ),
    ]
