# Generated by Django 4.1.2 on 2023-02-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coin_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Today_OHLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_open', models.CharField(max_length=120)),
                ('time_close', models.CharField(max_length=120)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.IntegerField()),
                ('market_cap', models.IntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin_profile.coinprofile')),
            ],
            options={
                'verbose_name_plural': 'get_today_OHLC',
            },
        ),
    ]
