# Generated by Django 4.1.2 on 2023-03-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_today_ohlc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='today_ohlc',
            name='close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='today_ohlc',
            name='open',
            field=models.FloatField(null=True),
        ),
    ]
