# Generated by Django 4.1.2 on 2023-03-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_today_ohlc', '0002_alter_today_ohlc_close_alter_today_ohlc_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='today_ohlc',
            options={'verbose_name_plural': 'Coin-today-data'},
        ),
    ]
