# Generated by Django 4.1.2 on 2023-03-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_today_ohlc', '0003_alter_today_ohlc_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='today_ohlc',
            name='high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='today_ohlc',
            name='low',
            field=models.FloatField(null=True),
        ),
    ]
