# Generated by Django 4.1.2 on 2023-03-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_today_ohlc', '0004_alter_today_ohlc_high_alter_today_ohlc_low'),
    ]

    operations = [
        migrations.AlterField(
            model_name='today_ohlc',
            name='market_cap',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='today_ohlc',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
