# Generated by Django 4.1.2 on 2023-03-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_today_ohlc', '0005_alter_today_ohlc_market_cap_alter_today_ohlc_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='today_ohlc',
            old_name='close',
            new_name='day_high',
        ),
        migrations.RenameField(
            model_name='today_ohlc',
            old_name='high',
            new_name='day_low',
        ),
        migrations.RenameField(
            model_name='today_ohlc',
            old_name='low',
            new_name='previousClose',
        ),
        migrations.RemoveField(
            model_name='today_ohlc',
            name='time_close',
        ),
        migrations.RemoveField(
            model_name='today_ohlc',
            name='time_open',
        ),
        migrations.AddField(
            model_name='today_ohlc',
            name='year_high',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='today_ohlc',
            name='year_low',
            field=models.FloatField(null=True),
        ),
    ]
