# Generated by Django 4.1.2 on 2023-03-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_today_ohlc', '0006_rename_close_today_ohlc_day_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='today_ohlc',
            name='avg_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='today_ohlc',
            name='price_avg200',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='today_ohlc',
            name='price_avg50',
            field=models.FloatField(null=True),
        ),
    ]
