# Generated by Django 4.1.2 on 2023-03-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_profile', '0011_alter_coinprofile_description'),
        ('crypto_historical_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='CryptoHistoricalData',
        ),
    ]
