# Generated by Django 4.1.2 on 2023-03-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_historical_data', '0002_rename_stock_cryptohistoricaldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoHistoricalData',
        ),
    ]
