# Generated by Django 4.1.2 on 2023-03-23 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coin_profile', '0011_alter_coinprofile_description'),
        ('crypto_historical_data', '0003_delete_cryptohistoricaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoHistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin_profile.coinprofile')),
            ],
            options={
                'verbose_name_plural': 'Crypto-Historical-Data',
            },
        ),
    ]
