# Generated by Django 4.1.2 on 2023-02-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coin_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterTweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=120)),
                ('user_image_link', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
                ('is_retweet', models.BooleanField()),
                ('retweet_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('status_id', models.CharField(max_length=120)),
                ('media_link', models.CharField(max_length=120, null=True)),
                ('youtube_link', models.CharField(max_length=120, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin_profile.coinprofile')),
            ],
            options={
                'verbose_name_plural': 'Twitter Tweets',
            },
        ),
    ]
