# Generated by Django 4.1.2 on 2023-03-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_twitter_tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twittertweets',
            options={'verbose_name_plural': 'Twitter-tweets-regarding-a-coin'},
        ),
    ]
