# Generated by Django 4.1.2 on 2023-03-13 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin_profile', '0011_alter_coinprofile_description'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancechange',
            name='coin_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='coin_profile.coinprofile'),
            preserve_default=False,
        ),
    ]
