# Generated by Django 4.1.2 on 2023-03-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_performancechange_year_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancechange',
            name='half_yearly_percentage_change',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performancechange',
            name='monthly_percentage_change',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performancechange',
            name='quarterly_percentage_change',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performancechange',
            name='weekly_percentage_change',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performancechange',
            name='year_to_date',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performancechange',
            name='yearly_percentage_change',
            field=models.FloatField(null=True),
        ),
    ]
