# Generated by Django 4.1.2 on 2023-02-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
                ('is_new', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('type', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=200, null=True)),
                ('open_source', models.BooleanField()),
                ('started_at', models.DateField(auto_now=True)),
                ('development_status', models.CharField(max_length=200)),
                ('hardware_wallet', models.CharField(max_length=200)),
                ('proof_type', models.CharField(max_length=200)),
                ('org_structure', models.CharField(max_length=200)),
                ('hash_algorithm', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Coin Profile',
            },
        ),
    ]
