# Generated by Django 4.1.2 on 2023-02-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_profile', '0002_alter_coinprofile_development_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinprofile',
            name='hash_algorithm',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coinprofile',
            name='org_structure',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
