# Generated by Django 4.1.2 on 2023-03-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_profile', '0004_alter_coinprofile_open_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinprofile',
            name='hardware_wallet',
            field=models.BooleanField(null=True),
        ),
    ]
