# Generated by Django 4.1.2 on 2023-03-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_profile', '0005_alter_coinprofile_hardware_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinprofile',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
