# Generated by Django 4.1.2 on 2023-03-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_profile', '0006_alter_coinprofile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinprofile',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='coinprofile',
            name='is_new',
            field=models.BooleanField(null=True),
        ),
    ]
