# Generated by Django 4.1.2 on 2023-03-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_profile', '0007_alter_coinprofile_is_active_alter_coinprofile_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinprofile',
            name='development_status',
        ),
        migrations.RemoveField(
            model_name='coinprofile',
            name='hardware_wallet',
        ),
        migrations.RemoveField(
            model_name='coinprofile',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='coinprofile',
            name='message',
        ),
        migrations.RemoveField(
            model_name='coinprofile',
            name='open_source',
        ),
        migrations.RemoveField(
            model_name='coinprofile',
            name='rank',
        ),
    ]
