# Generated by Django 4.1.2 on 2023-03-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_profile', '0008_remove_coinprofile_development_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinprofile',
            options={'verbose_name_plural': 'Coin-Profile(all-coins)'},
        ),
    ]
