# Generated by Django 4.1.2 on 2023-03-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_profile', '0009_alter_coinprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinprofile',
            name='proof_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
