# Generated by Django 4.1.2 on 2023-02-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExplosureLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explorer_link_1', models.CharField(max_length=120)),
                ('explorer_link_2', models.CharField(max_length=120)),
                ('explorer_link_3', models.CharField(max_length=120)),
                ('explorer_link_4', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Explosure Links',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=120)),
                ('reddit', models.CharField(max_length=120)),
                ('source_code', models.CharField(max_length=120)),
                ('website', models.CharField(max_length=120)),
                ('youtube_link', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Social Links',
            },
        ),
    ]
