# Generated by Django 4.1.2 on 2023-02-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explosurelinks',
            name='explorer_link_1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='explosurelinks',
            name='explorer_link_2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='explosurelinks',
            name='explorer_link_3',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='explosurelinks',
            name='explorer_link_4',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
