# Generated by Django 4.1.2 on 2023-03-01 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_profile', '0003_alter_coinprofile_hash_algorithm_and_more'),
        ('coin_links', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExplosureLinks',
            new_name='ExplorerLinks',
        ),
        migrations.AlterModelOptions(
            name='explorerlinks',
            options={'verbose_name_plural': 'Explorer Links'},
        ),
    ]
