# Generated by Django 4.1.2 on 2023-03-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_links', '0002_rename_explosurelinks_explorerlinks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='explorerlinks',
            options={'verbose_name_plural': 'Explorer-links-of-coin'},
        ),
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name_plural': 'Social-links-of-coin'},
        ),
    ]
