# Generated by Django 4.1.2 on 2023-02-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_links', '0002_alter_explosurelinks_explorer_link_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='facebook',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='reddit',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='source_code',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='website',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='youtube_link',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
