# Generated by Django 4.1.2 on 2023-03-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_links', '0006_remove_explorerlinks_explorer_link_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explorerlinks',
            name='explorer_links',
        ),
        migrations.AddField(
            model_name='explorerlinks',
            name='explorer_link_1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='explorerlinks',
            name='explorer_link_2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='explorerlinks',
            name='explorer_link_3',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='explorerlinks',
            name='explorer_link_4',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
